### PR TITLE
Fix 'Accessing PropTypes via the main React package is deprecated.'

### PR DESCRIPTION
**Pull request by mdenisov**
Fix 'Accessing PropTypes via the main React package is deprecated.'

### CODE REVIEW

**Comment by noamokman** [comment]
This closes #108.
Can this be merged?

**Comment by noamokman** [comment]
@sars ?

**Comment by ankitpatial** [comment]
@sars thank you for this nice lib. I am sure you can catch some time to merge a pr #116 related to prop-types, have a look at it and merge it in. I am sure like me there be lot more users who direly  need this change to upgrade their app to react v16.x.x

**Comment by ankitpatial** [comment]
Seem like there is multiple PR for same purpose, Please merge any of them you may ignore other

**Comment by ankitpatial** [comment]
@sars can you please merge the PR that is block many us to upgrade our apps.

**Pull request closed without merging**
