### PR TITLE
Support ImmutableJS 

### PR DESCRIPTION
**Pull request by xesrevinu**
``` js
// server.js
const selectLoadedState = (state) => {
  return state.get('reduxAsyncConnect').loaded
}
const component = (
  <Provider store={store} key='provider'>
        <ReduxAsyncConnect {...renderProps} selectLoadedState={selectLoadedState}/>
  </Provider>
)
```

``` js
// client.js
const component = (
  <Router history={browserHistory}
          render={(props) => <ReduxAsyncConnect {...props} selectLoadedState={selectLoadedState}/>}>
    {routes}
  </Router>
)
```

Immutable ok 😇

### CODE REVIEW

**Comment by sars** [comment]
@xiaokekeT Hi!
https://github.com/Rezonans/redux-async-connect/pull/45/files#diff-6dc2b4a46b3cdfd95dffadba329d8868R47
It seems this won't work with Immutable.js ....

**Comment by xesrevinu** [comment]
@sars Hi 😁
https://github.com/Rezonans/redux-async-connect/pull/45/files#diff-1311f19afc0c23c81adc816eec36584dL73

``` js
import { combineReducers } from 'redux-immutablejs'
export default combineReducers({
  routing,
  reduxAsyncConnect
})

```

If you don't do that Can't get the correct value
There is a better way?

**Comment by sars** [comment]
@xiaokekeT I'm thinking ...
May be it make sense even to throw away reducer ... or make usage optional...
but anyway we need to save somewhere that initial data is fetched already on server, so, no need to refetch it on client...

**Comment by xesrevinu** [comment]
He is optional, you won't have to write if you are not immutable. Client/server `selectLoadedState` is a must If client load data is also using the loaded

Thank you😄
my english is very poor 
I hope you can understand
@hung-phan what do you think?

**Comment by hung-phan** [comment]
Uhm. It must include `selectLoadedState`. Additionally, we have to write the reducer to update the state of `redux-async-connect`.

Agree, @sars. The part of writing the reducer is verbose (gladly, we only have to write it once).

**Comment by sars** [comment]
Guys, may be it just make sense to write another immutable-compatible reducer that will be equivalent of old reducer. and everybody can use that reducer they want...

**Comment by xesrevinu** [comment]
What should I do now？

**Comment by xesrevinu** [comment]
Now i use the [redial](https://github.com/markdalgleish/redial) solved my problem
Thank you

**Pull request closed without merging**
