### PR TITLE
feat(loadAsyncData): check window object for server side

### PR DESCRIPTION
**Pull request by evenchange4**
Try to solve the PR at [#872](https://github.com/erikras/react-redux-universal-hot-example/pull/872)

### CODE REVIEW

**Comment by sars** [comment]
@evenchange4 , to be honest, i didn't catch what this PR solves. 
this code is never called on server side...

**Comment by evenchange4** [comment]
It solves the same thing what [#872](https://github.com/erikras/react-redux-universal-hot-example/pull/872) does, but checking `__SERVER__` inside the `redux-async-connect`.
I mean the server side render.

cc @sars

**Comment by sars** [comment]
@evenchange4, take a look please:
https://github.com/Rezonans/redux-async-connect/tree/v1

there is new interface for @asyncConnect decorator in this version. 

Now you can use it like: 

``` js
@asyncConnect([
  {key: 'lunch', promise: ({params, helpers}) => helpers.client.get('/lunches/' + params.lunchId), group: 'smth'}
])
```

and then in your client.js:

``` js
const component = (
  <Router render={(props) =>
        <ReduxAsyncConnect {...props} filter={item => item.group === 'smth'} helpers={{client}} />
      } history={browserHistory}>
    {getRoutes(store, client)}
  </Router>
);
```

and server.js:

``` js
loadOnServer({...renderProps, store, helpers: {client}}).then(() => {
  // ...
}
```

Does it works for you?

**Comment by evenchange4** [comment]
okay works for me
@sars thanks! 
close it

**Pull request closed without merging**
