### PR TITLE
Handle routes that have defined components property.

### PR DESCRIPTION
**Pull request by HorizonXP**
https://github.com/rackt/react-router allows `Route` to be defined with a `components` property, as illustrated in this example: https://github.com/rackt/react-router/blob/master/examples/sidebar/app.js#L107

When `eachComponents` receives the `components` array, it contains an `Object` with keys mapped to a `Component`. 

This pull request modifies how `eachComponents` traverses the `components` array so it can handle these objects.

I've likely missed the original intent of your code as you wrote it, so it would be helpful if you could review and comment, so I can update my pull request if necessary.

### CODE REVIEW

**Comment by sars** [comment]
Hey, @HorizonXP ,
Thanks for PR

I don't see any differences between 

```
for (const key of components[i]) {
```

and 

```
for (let [key, value] of Object.entries(components[i])) {
```

except you also define value var that is actually unused...

About Idea of eachComponents function - yes, you got it...

**Comment by HorizonXP** [comment]
So I agree that there isn't much different, but your version transpiles to this:

``` javascript
/**
 * We need to iterate over all components for specified routes.
 * Components array can include objects if named components are used:
 * https://github.com/rackt/react-router/blob/latest/docs/API.md#named-components
 *
 * @param components
 * @param iterator
 */

function eachComponents(components, iterator) {
  for (var i = 0, l = components.length; i < l; i++) {
    // eslint-disable-line id-length
    if (_typeof(components[i]) === 'object') {
      var _iteratorNormalCompletion = true;
      var _didIteratorError = false;
      var _iteratorError = undefined;

      try {
        for (var _iterator = components[i][Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
          var key = _step.value;

          iterator(components[i][key], i, key);
        }
      } catch (err) {
        _didIteratorError = true;
        _iteratorError = err;
      } finally {
        try {
          if (!_iteratorNormalCompletion && _iterator.return) {
            _iterator.return();
          }
        } finally {
          if (_didIteratorError) {
            throw _iteratorError;
          }
        }
      }
    } else {
      iterator(components[i], i);
    }
  }
}
```

Which yields the following stack trace:

``` javascript
Unhandled promise rejection TypeError: components[i][Symbol.iterator] is not a function
Stack trace:
eachComponents@http://localhost:3000/static/frontend/js/bundle.js:73631:31
filterAndFlattenComponents@http://localhost:3000/static/frontend/js/bundle.js:73658:4
loadAsyncData@http://localhost:3000/static/frontend/js/bundle.js:73736:44
componentWillReceiveProps@http://localhost:3000/static/frontend/js/bundle.js:73719:8
ReactCompositeComponentMixin.updateComponent@http://localhost:3000/static/frontend/js/bundle.js:65774:10
ReactPerf.measure/wrapper@http://localhost:3000/static/frontend/js/bundle.js:9635:17
ReactCompositeComponentMixin.receiveComponent@http://localhost:3000/static/frontend/js/bundle.js:65721:6
ReactReconciler.receiveComponent@http://localhost:3000/static/frontend/js/bundle.js:11926:6
ReactCompositeComponentMixin._updateRenderedComponent@http://localhost:3000/static/frontend/js/bundle.js:65878:8
ReactCompositeComponentMixin._performComponentUpdate@http://localhost:3000/static/frontend/js/bundle.js:65860:6
ReactCompositeComponentMixin.updateComponent@http://localhost:3000/static/frontend/js/bundle.js:65789:8
ReactPerf.measure/wrapper@http://localhost:3000/static/frontend/js/bundle.js:9635:17
ReactCompositeComponentMixin.performUpdateIfNecessary@http://localhost:3000/static/frontend/js/bundle.js:65737:8
ReactReconciler.performUpdateIfNecessary@http://localhost:3000/static/frontend/js/bundle.js:11941:6
runBatchedUpdates@http://localhost:3000/static/frontend/js/bundle.js:9933:6
Mixin.perform@http://localhost:3000/static/frontend/js/bundle.js:16922:14
Mixin.perform@http://localhost:3000/static/frontend/js/bundle.js:16922:14
.perform@http://localhost:3000/static/frontend/js/bundle.js:9890:13
flushBatchedUpdates@http://localhost:3000/static/frontend/js/bundle.js:9951:8
ReactPerf.measure/wrapper@http://localhost:3000/static/frontend/js/bundle.js:9635:17
Mixin.closeAll@http://localhost:3000/static/frontend/js/bundle.js:16988:12
Mixin.perform@http://localhost:3000/static/frontend/js/bundle.js:16935:12
ReactDefaultBatchingStrategy.batchedUpdates@http://localhost:3000/static/frontend/js/bundle.js:33857:8
enqueueUpdate@http://localhost:3000/static/frontend/js/bundle.js:9980:6
enqueueUpdate@http://localhost:3000/static/frontend/js/bundle.js:21376:4
ReactUpdateQueue.enqueueSetState@http://localhost:3000/static/frontend/js/bundle.js:21542:6
ReactComponent.prototype.setState@http://localhost:3000/static/frontend/js/bundle.js:33284:4
handleChange@http://localhost:3000/static/frontend/js/bundle.js:59386:12
dispatch/<@http://localhost:3000/static/frontend/js/bundle.js:37370:15
dispatch@http://localhost:3000/static/frontend/js/bundle.js:37369:6
middleware/</<@http://localhost:3000/static/frontend/js/bundle.js:15872:1
timeoutMiddleware/</</<@http://localhost:3000/static/frontend/js/bundle.js:22875:97
cookieMiddleware/</</<@http://localhost:3000/static/frontend/js/bundle.js:22780:118
fetchMiddleware/</<@http://localhost:3000/static/frontend/js/bundle.js:36206:175
exports.default/</</<@http://localhost:3000/static/frontend/js/bundle.js:46263:21
bearer/</</<@http://localhost:3000/static/frontend/js/bundle.js:74483:272
exports.default/</</<@http://localhost:3000/static/frontend/js/bundle.js:46179:1
exports.default/</</<@http://localhost:3000/static/frontend/js/bundle.js:46142:1
thunkMiddleware/</<@http://localhost:3000/static/frontend/js/bundle.js:76567:75
effects/</<@http://localhost:3000/static/frontend/js/bundle.js:9705:72
exports.default/</<@http://localhost:3000/static/frontend/js/bundle.js:46213:19
multi/</<@http://localhost:3000/static/frontend/js/bundle.js:76543:14
bindActionCreator/<@http://localhost:3000/static/frontend/js/bundle.js:76657:13
doSubmit/<@http://localhost:3000/static/frontend/js/bundle.js:75811:12
notify/</run@http://localhost:3000/static/frontend/js/bundle.js:39424:48
notify/<@http://localhost:3000/static/frontend/js/bundle.js:39435:29
flush@http://localhost:3000/static/frontend/js/bundle.js:38074:6
```

My version transpiles to this:

``` javascript
/**
 * We need to iterate over all components for specified routes.
 * Components array can include objects if named components are used:
 * https://github.com/rackt/react-router/blob/latest/docs/API.md#named-components
 *
 * @param components
 * @param iterator
 */

function eachComponents(components, iterator) {
  for (var i = 0, l = components.length; i < l; i++) {
    // eslint-disable-line id-length
    if (_typeof(components[i]) === 'object') {
      var _iteratorNormalCompletion = true;
      var _didIteratorError = false;
      var _iteratorError = undefined;

      try {
        for (var _iterator = Object.entries(components[i])[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
          var _step$value = _slicedToArray(_step.value, 2);

          var key = _step$value[0];
          var value = _step$value[1];

          console.log(key, value);
          iterator(components[i][key], i, key);
        }
      } catch (err) {
        _didIteratorError = true;
        _iteratorError = err;
      } finally {
        try {
          if (!_iteratorNormalCompletion && _iterator.return) {
            _iterator.return();
          }
        } finally {
          if (_didIteratorError) {
            throw _iteratorError;
          }
        }
      }
    } else {
      iterator(components[i], i);
    }
  }
}
```

Which doesn't throw the error.

**Comment by sars** [comment]
@HorizonXP it doesn't throw error for me to be honest...
I'm wandering , why...
anyway - it's worth to change components[i][key] to value in your PR

**Comment by HorizonXP** [comment]
Done.

**Comment by sars** [comment]
@HorizonXP , do you have any ideas why you get this error and i do not?..

**Comment by HorizonXP** [comment]
Not sure why, but this issue (https://github.com/babel/babel-loader/issues/84) led me to a potential cause and solution.

**Comment by sars** [comment]
@HorizonXP , thanks! merged

**Pull request merged**
